require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OauthSamplesController do

  # This should return the minimal set of attributes required to create a valid
  # OauthSample. As you add validations to OauthSample, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all oauth_samples as @oauth_samples" do
      oauth_sample = OauthSample.create! valid_attributes
      get :index
      assigns(:oauth_samples).should eq([oauth_sample])
    end
  end

  describe "GET show" do
    it "assigns the requested oauth_sample as @oauth_sample" do
      oauth_sample = OauthSample.create! valid_attributes
      get :show, :id => oauth_sample.id
      assigns(:oauth_sample).should eq(oauth_sample)
    end
  end

  describe "GET new" do
    it "assigns a new oauth_sample as @oauth_sample" do
      get :new
      assigns(:oauth_sample).should be_a_new(OauthSample)
    end
  end

  describe "GET edit" do
    it "assigns the requested oauth_sample as @oauth_sample" do
      oauth_sample = OauthSample.create! valid_attributes
      get :edit, :id => oauth_sample.id
      assigns(:oauth_sample).should eq(oauth_sample)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OauthSample" do
        expect {
          post :create, :oauth_sample => valid_attributes
        }.to change(OauthSample, :count).by(1)
      end

      it "assigns a newly created oauth_sample as @oauth_sample" do
        post :create, :oauth_sample => valid_attributes
        assigns(:oauth_sample).should be_a(OauthSample)
        assigns(:oauth_sample).should be_persisted
      end

      it "redirects to the created oauth_sample" do
        post :create, :oauth_sample => valid_attributes
        response.should redirect_to(OauthSample.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved oauth_sample as @oauth_sample" do
        # Trigger the behavior that occurs when invalid params are submitted
        OauthSample.any_instance.stub(:save).and_return(false)
        post :create, :oauth_sample => {}
        assigns(:oauth_sample).should be_a_new(OauthSample)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OauthSample.any_instance.stub(:save).and_return(false)
        post :create, :oauth_sample => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested oauth_sample" do
        oauth_sample = OauthSample.create! valid_attributes
        # Assuming there are no other oauth_samples in the database, this
        # specifies that the OauthSample created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OauthSample.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => oauth_sample.id, :oauth_sample => {'these' => 'params'}
      end

      it "assigns the requested oauth_sample as @oauth_sample" do
        oauth_sample = OauthSample.create! valid_attributes
        put :update, :id => oauth_sample.id, :oauth_sample => valid_attributes
        assigns(:oauth_sample).should eq(oauth_sample)
      end

      it "redirects to the oauth_sample" do
        oauth_sample = OauthSample.create! valid_attributes
        put :update, :id => oauth_sample.id, :oauth_sample => valid_attributes
        response.should redirect_to(oauth_sample)
      end
    end

    describe "with invalid params" do
      it "assigns the oauth_sample as @oauth_sample" do
        oauth_sample = OauthSample.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OauthSample.any_instance.stub(:save).and_return(false)
        put :update, :id => oauth_sample.id, :oauth_sample => {}
        assigns(:oauth_sample).should eq(oauth_sample)
      end

      it "re-renders the 'edit' template" do
        oauth_sample = OauthSample.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OauthSample.any_instance.stub(:save).and_return(false)
        put :update, :id => oauth_sample.id, :oauth_sample => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested oauth_sample" do
      oauth_sample = OauthSample.create! valid_attributes
      expect {
        delete :destroy, :id => oauth_sample.id
      }.to change(OauthSample, :count).by(-1)
    end

    it "redirects to the oauth_samples list" do
      oauth_sample = OauthSample.create! valid_attributes
      delete :destroy, :id => oauth_sample.id
      response.should redirect_to(oauth_samples_url)
    end
  end

end
